algorithm: fullysupervised
save_dir: ./saved_models/usb_nlp
save_name: fully_set14_ver1
resume: True
load_path: ./saved_models/usb_nlp/fully_set14_ver1/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 100
num_train_iter: 102400
num_warmup_iter: 5120
num_log_iter: 256
num_eval_iter: 2048
num_labels: 250
batch_size: 16
eval_batch_size: 16
ema_m: 0.0
uratio: 1
use_cat: False
optim: AdamW
lr: 5e-05
momentum: 0.9
weight_decay: 0.0005
layer_decay: 0.75
amp: False
clip: 0.0
net: bert_base_uncased
net_from_name: False
data_dir: ./data
dataset: set14_ver1
train_sampler: RandomSampler
num_classes: 3
num_workers: 2
max_length: 512
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10030
dist_backend: nccl
gpu: 0
